### ISSUE TITLE
有没有办法和其他的UI框架混用

### ISSUE THREAD

**Issue by doglex** [vexip-ui/vexip-ui#448]
### Description

当我在一个用Element Plus开发的工程中引入 vexip-ui，想使用其中一部分控件
 并且使用import 'vexip-ui/css/index.css'  来导入vexip的样式
但是vexip-ui的样式会覆盖掉 element的样式，原来的按钮样式没掉了
有没有方法隔离出来

### Validations

- [X] Ensure this issue neither a bug report nor a feature proposal.
- [X] Read the [Contributing Guidelines](https://github.com/vexip-ui/vexip-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.vexipui.com/).
- [X] Check that there isn't [already an issue](https://github.com/vexip-ui/vexip-ui/issues) that descript the same thing to avoid creating a duplicate.

**Comment by qmhc** [comment]
能否描述一下具体的样式呢？Vexip 的样式类型都带有 `vxp` 前缀并且全部为标准的 BEM 命名，同时除了下面列举之外无其他全局样式；而 Element Plus 则带有 `el` 前缀，不应该出现冲突才对。

唯一的全局样式：

```css
body {
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  -webkit-tap-highlight-color: transparent;
}
```
